# -*- coding: utf-8 -*-
"""Day-21(EDA Using Bivariate and MultiVariate Analysis).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mu0TY6-teZFM8ANuWWwCl9ut3r7kCSpz
"""

import pandas as pd
import seaborn as sns

tips = sns.load_dataset("tips")
titanic = pd.read_csv("/content/tested.csv")
flights = sns.load_dataset("flights")
iris = sns.load_dataset("iris")

print(tips.head(100))

"""# Bi-Variate Analysis:

# 1.Scatterplot (Numerical - Numerical)
"""

sns.scatterplot(x='total_bill', y='tip',data=tips)

"""#scaterplot(Numerical - Numerical)->Multivariate"""

sns.scatterplot(x = 'total_bill', y = 'tip' , hue = 'sex', style = 'smoker', size = 'time', data = tips)

"""# Bar plot(Numerical - Categorical)"""

titanic.head()
sns.barplot(x = 'Pclass', y = 'Age', hue = 'Sex',  data = titanic)

"""# Box plot(Numerical - Categorical)"""

sns.boxplot(x = 'Survived', y = 'Age', hue = 'Sex',  data = titanic)

"""# 4.Distplot(Numerical - Categorical) ->
 ## probability Density Function
"""

sns.kdeplot(data=titanic[titanic['Survived'] == 0], x='Age', label='Survived = 0', fill=True)
sns.kdeplot(data=titanic[titanic['Survived'] == 1], x='Age', label='Survived = 1', fill=True)



"""# 5.HeatMap (Categorical - Categorical)"""

sns.heatmap(pd.crosstab(titanic['Pclass'], titanic['Survived']))

"""# ClusterMap(Categorical - Categorical)"""

sns.clustermap(pd.crosstab(titanic['SibSp'], titanic['Survived']))

"""# Pairplot"""

iris.head()
sns.pairplot(iris)

sns.pairplot(iris, hue = 'species')

"""# Line plot(Numerical - Numerical)"""

flights.head()

sns.heatmap(flights.pivot_table(index='month', columns='year', values='passengers'))

sns.clustermap(flights.pivot_table(index='month', columns='year', values='passengers'))