# -*- coding: utf-8 -*-
"""Day 20-EDA using univariate Analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/day-20-eda-using-univariate-analysis-py-4b30a16f-5b8b-455e-8d4c-d5260331a691.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250223/auto/storage/goog4_request%26X-Goog-Date%3D20250223T183556Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D659140007b7ac734c73d67f2160cacc243a46f4714b91121ac7b52dcff1efaf2bb7aebd0e89d2a2dbd1d17a3541c1784d0e59c1b2d956b0bb6bbdbd519933bf648d3ae69315b1a62fe1144f4b87fb85f7eefeab424472c549e5453bd972a0f17c4c868d724218e7033807ddc3739fe9e05fe4f01cec9b1125ee3a0dfb7ae1b6df648dd55e342722f54ba864b1c37c393fcac2ae9f022109e390def85af0385306c3f273e3dce885306dd8b12c5fed0b84d30b33e8796986a6761d46104101e82bbecec0d6d2555fa712d315b289087720bbb154da9fff1f784cd0dc22bcfdec22983ab9678c803e0f037d8440a2185a320a7a280cad43ba5d7fbdbe053caab87

# Univariate Analysis

# Data two Types 1:Categorical Data & 2:Numerical Data

# Categorical Data

# a.Count Plot
"""

import pandas as pd
import seaborn as sns

df = pd.read_csv('/kaggle/input/titanic/train.csv')
df.head()

#sns.countplot(df['Survived'])
df['Survived'].value_counts().plot(kind = 'bar')

df['Name'].value_counts().plot(kind = 'bar')

df['Pclass'].value_counts().plot(kind = 'bar')

"""# b.Pie_Chart"""

df['Survived'].value_counts().plot(kind = 'pie')

df['Survived'].value_counts().plot(kind = 'pie',autopct = '%.2f')

"""# 2.Numerical Data

# a.Histogram:
"""

import pandas as pd
import matplotlib.pyplot as plt

plt.hist(df['Age'])

plt.hist(df['Age'],bins = 50)

"""# b.Displot"""

sns.displot(df['Age'])

"""# C.Boxplot:"""

sns.boxplot(df['Age'])

sns.boxplot(df['Fare'])

df['Age'].min()

df['Age'].max()

df['Age'].mean()

df['Age'].skew()