# -*- coding: utf-8 -*-
"""Day 20-EDA using univariate Analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/day-20-eda-using-univariate-analysis-py-a6d7de02-c948-428f-a0d3-56ab2e08e281.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250223/auto/storage/goog4_request%26X-Goog-Date%3D20250223T184423Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3Da7fa94b821b7a0b09b784bcd8ba9eaf6a8bd3686d044d4cea80c59c98f7b5d8368dfd6ad77c24da30c1e000210e81ff12c23f6ad4afd5c1be532c1e1aec3a686dac6fe1376cc9b9585ff574449d5c937c758bf6e61b9c16c04546533abe8e4bdfdcd840c360e098e7ace5b8f62e8ca28bc2f29490217ff6d5780036d8ed2d35105eb2569ef3b3d0127c1bfab4f8f664dddb10620fa6798675c29082224a44029aceaaace5b1e8ca4fe63a64d95cbc0e53fe60d73f6fbbf3fed566a8a58a1a8ed8e753c412f166b85e47d19c3eed648c4f403e84edf4922dead6cc25627ce851aa951e52c6d3d63ecd9b16fc98a2244428b2a37b0d41ac0a3362c259fb0551155

# Univariate Analysis Using Diabetes Patient

> Add blockquote

# Data two Types 1:Categorical Data & 2:Numerical Data

# Categorical Data

# a.Count Plot
"""

import pandas as pd
import seaborn as sns

df = pd.read_csv('/kaggle/input/diabetes-dataset-for-beginners/diabetes.csv')
df.head()

#sns.countplot(df['Outcome'])
df['Outcome'].value_counts().plot(kind = 'bar')

df['BloodPressure'].value_counts().plot(kind = 'bar')

df['DiabetesPedigreeFunction'].value_counts().plot(kind = 'bar')

"""# b.Pie_Chart"""

df['DiabetesPedigreeFunction'].value_counts().plot(kind = 'pie')

df['Insulin'].value_counts().plot(kind = 'pie',autopct = '%.2f')

"""# 2.Numerical Data

# a.Histogram:
"""

import pandas as pd
import matplotlib.pyplot as plt

plt.hist(df['Pregnancies'])

plt.hist(df['Pregnancies'],bins = 50)

"""# b.Displot"""

sns.displot(df['Age'])

"""# C.Boxplot:"""

sns.boxplot(df['Age'])

sns.boxplot(df['BloodPressure'])

df['Age'].min()

df['Age'].max()

df['Age'].mean()

df['Age'].skew()
